services:
    thecocktail_aws_polly.fieldtype.ezawspollyfile:
        class: TheCocktail\EzAwsPollyBundle\Core\FieldType\AwsPollyFile\Type
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezawspollyfile}

    thecocktail_aws_polly.fieldtype.indexable.awspollybinaryfile:
        class: "%ezpublish.fieldType.indexable.ezbinaryfile.class%"
        tags:
          - {name: ezpublish.fieldType.indexable, alias: ezawspollyfile}

    thecocktail_aws_polly.fieldtype.ezawspollyfile.converter:
        class: "%ezpublish.fieldType.ezbinaryfile.converter.class%"
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: ezawspollyfile}

    thecocktail_aws_polly.fieldtype.ezawspollyfile.externalStorage:
        class: "%ezpublish.fieldType.ezbinaryfile.externalStorage.class%"
        arguments:
            - "@ezpublish.fieldType.ezbinaryfile.storage_gateway"
            - "@ezpublish.fieldType.ezbinaryfile.io_service"
            - "@ezpublish.fieldType.ezbinaryfile.pathGenerator"
            - "@ezpublish.core.io.mimeTypeDetector"
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: ezawspollyfile}

    thecocktail_aws_polly.field_type_processor.ezawspollyfile:
        class: "%ezpublish_rest.field_type_processor.ezbinaryfile.class%"
        factory: ["@ezpublish_rest.factory", getBinaryFileFieldTypeProcessor]
        arguments:
            - "@ezpublish.core.io.default_url_decorator"
        tags:
            - { name: ezpublish_rest.field_type_processor, alias: ezawspollyfile }

    thecocktail_aws_polly.fieldtype.ezawspollyfile.externalStorage:
        class: "%ezpublish.fieldType.ezbinaryfile.externalStorage.class%"
        arguments:
            - "@ezpublish.fieldType.ezbinaryfile.storage_gateway"
            - "@ezpublish.fieldType.ezbinaryfile.io_service"
            - "@ezpublish.fieldType.ezbinaryfile.pathGenerator"
            - "@ezpublish.core.io.mimeTypeDetector"
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: ezawspollyfile}
