imports:
    - { resource: 'fieldtypes.yaml' }

services:
    ez_aws_polly.client:
        class: TheCocktail\Aws\Polly\TheCocktailPollyClient
        arguments:
            - '@ez_aws_polly.speech_builder'
            - '@oneup_flysystem.polly_files_filesystem'
            -
                version: 'latest'
                region: '%aws_region%'
                credentials:
                    key: '%aws_key%'
                    secret: '%aws_secret%'

    ez_aws_polly.speech_builder:
        class: TheCocktail\Aws\Polly\SpeechBuilder

    ez_aws_polly.transformer.ssml_transformer:
        class: TheCocktail\EzAwsPollyBundle\Transformer\SSMLTransformer
        arguments:
            - '@maxbeckers_amazon_alexa.ssml_generator'

    ez_aws_polly.core.speech_creator:
        class: TheCocktail\EzAwsPollyBundle\Core\SpeechCreator
        arguments:
           - '@ezpublish.api.service.content'
           - '@ez_aws_polly.transformer.ssml_transformer'
           - '@ez_aws_polly.client'
